/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpusqu;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.util.concurrent.TimeUnit;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

// Abstract class for database connection
abstract class DatabaseConnection {
    static final String DB_URL = "jdbc:mysql://localhost:3306/perpusqu";
    static final String USER = "root";
    static final String PASSWORD = "";

    // Abstract method for getting a database connection
    abstract Connection getConnection() throws SQLException;
}

// Class that extends the abstract class and implements the getConnection method
class DatabaseConnector extends DatabaseConnection {
    @Override
    Connection getConnection() throws SQLException {
        return DriverManager.getConnection(DB_URL, USER, PASSWORD);
    }
}

public class InterfacePengembalian extends javax.swing.JFrame {

    private final DatabaseConnection dbConnection = new DatabaseConnector();
    // Hapus 'static final String query', kita buat query di dalam method
        
    DefaultTableModel model;
    
    String unama;
    String unim;
    
    // <-- PERUBAHAN: Tambahkan variabel untuk menyimpan ID yang dipilih
    private int selectedPeminjamanId = -1;
    
    public void setUserInfo(String nama, String nim) {
        
        this.unama = nama;
        this.unim = nim;
        TF_nama.setText(unama);
        TF_NIM.setText(unim);
        displayPeminjamanTable();
    }
    
    public InterfacePengembalian() {
        initComponents();
        
        model = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Nama", "NIM", "Judul Buku", "Sisa Hari", "Denda"
            }
        ) {
            
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        
        TB_kembali.setModel(model);

        
        TB_kembali.getColumnModel().getColumn(0).setMinWidth(0);
        TB_kembali.getColumnModel().getColumn(0).setMaxWidth(0);
        TB_kembali.getColumnModel().getColumn(0).setWidth(0);
        
        TB_kembali.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int selectedRow = TB_kembali.getSelectedRow();
                if (selectedRow != -1) {
                    selectedPeminjamanId = (int) model.getValueAt(selectedRow, 0); // <-- Ambil ID
                    String nama = model.getValueAt(selectedRow, 1).toString();
                    String nim = model.getValueAt(selectedRow, 2).toString();
                    String judul = model.getValueAt(selectedRow, 3).toString();

                    // Set text fields
                    TF_nama.setText(nama);
                    TF_NIM.setText(nim);
                    TF_judul.setText(judul);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_nama = new javax.swing.JTextField();
        TF_NIM = new javax.swing.JTextField();
        TF_judul = new javax.swing.JTextField();
        btnKembalikan = new javax.swing.JButton();
        gotomenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_kembali = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama");

        jLabel3.setText("NIM");

        jLabel4.setText("Judul Buku");

        btnKembalikan.setText("Kembalikan");
        btnKembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembalikanActionPerformed(evt);
            }
        });

        gotomenu.setText("Menu");
        gotomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotomenuActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel2HierarchyChanged(evt);
            }
        });

        // Tampilan model di sini hanya placeholder, kode di konstruktor akan menggantinya
        TB_kembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "NIM", "Judul Buku", "Sisa Hari", "Denda"
            }
        ));
        jScrollPane1.setViewportView(TB_kembali);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("PENGEMBALIAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gotomenu)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(TF_NIM, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembalikan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TF_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TF_NIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKembalikan)
                .addGap(39, 39, 39)
                .addComponent(gotomenu)
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gotomenuActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        InterfaceUtama IU = new InterfaceUtama();
        IU.setUserInfo(unama, unim); // Kirim balik info user jika perlu
        IU.show();
        
        dispose();
    }                                        

    private void btnKembalikanActionPerformed(java.awt.event.ActionEvent evt) {
        
        String judul = TF_judul.getText();
        
        if (selectedPeminjamanId == -1 || judul.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data peminjaman dari tabel terlebih dahulu.");
            return;
        }

        updatePeminjamanTable(selectedPeminjamanId);
        
        updateBukuTable(judul);
 
        displayPeminjamanTable();
        
        TF_nama.setText(unama);
        TF_NIM.setText(unim);
        TF_judul.setText("");
        selectedPeminjamanId = -1;
    }                                             

    private void updatePeminjamanTable(int peminjamanId) {
        String deleteQuery = "DELETE FROM peminjaman WHERE ID = ?";

        try (
            Connection conn = dbConnection.getConnection();
            PreparedStatement deleteStmt = conn.prepareStatement(deleteQuery);
        ) {
            
            // Set parameter ID
            deleteStmt.setInt(1, peminjamanId);

            conn.setAutoCommit(false); // Start a transaction
            int rowsAffected = deleteStmt.executeUpdate();
            conn.commit(); // Commit the transaction
            
            if (rowsAffected > 0) {
                System.out.println("Data deleted from peminjaman table (ID: " + peminjamanId + ")!");
            } else {
                System.out.println("No data found to delete (ID: " + peminjamanId + ")");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void updateBukuTable(String judul) {
       
        String updateJumlahQuery = "UPDATE buku SET JumlahBuku = JumlahBuku + 1 WHERE Judul = ?";
        String updateStatusQuery = "UPDATE buku SET Status = 'Ada' WHERE Judul = ?";

        try (
            Connection conn = dbConnection.getConnection();
            PreparedStatement stmtJumlah = conn.prepareStatement(updateJumlahQuery);
            PreparedStatement stmtStatus = conn.prepareStatement(updateStatusQuery);
        ) {
            
            stmtJumlah.setString(1, judul);
            stmtStatus.setString(1, judul);

            
            stmtJumlah.executeUpdate();
            int rowsAffected = stmtStatus.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("Buku table updated: Status set to 'Ada'.");
            } else {
                System.out.println("Status buku tidak berubah (mungkin sudah 'Ada').");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void displayPeminjamanTable() {
        model.setRowCount(0);

        String selectQuery = "SELECT ID, Nama, NIM, Judul, TanggalKembali, DATEDIFF(TanggalKembali, CURDATE()) AS Sisa " +
                             "FROM peminjaman WHERE NIM = ?"; // <-- Filter berdasarkan NIM user

        try (
            Connection conn = dbConnection.getConnection();
            PreparedStatement stmt = conn.prepareStatement(selectQuery);
        ) {
            stmt.setString(1, this.unim); 
            
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                int sisa = rs.getInt("Sisa");
                int denda = (sisa < 0) ? 30000 : 0;
                
                model.addRow(new Object[]{
                    rs.getInt("ID"),
                    rs.getString("Nama"),
                    rs.getString("NIM"),
                    rs.getString("Judul"),
                    sisa,
                    denda
                });
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }                                             

    private void jPanel2HierarchyChanged(java.awt.event.HierarchyEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB_kembali;
    private javax.swing.JTextField TF_NIM;
    private javax.swing.JTextField TF_judul;
    private javax.swing.JTextField TF_nama;
    private javax.swing.JButton btnKembalikan;
    private javax.swing.JButton gotomenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

   
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
